### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by charleskawczynski** [Azzaare/Bibliography.jl#12]
Hello @Azzaare could we tag a new version? I'd like to start using recent changes in [ClimateMachine.jl](https://github.com/CliMa/ClimateMachine.jl)! 😄

**Comment by Azzaare** [comment]
Last version is tagged and submitted. Should be available in few dozens of minutes.

As I did rapidly, let me know if something is wrong (CI says no but well ...).

**Comment by charleskawczynski** [comment]
Thank you!
