### ISSUE TITLE
Would an `OrderedDict` make more sense than an `OrderedSet` for bibliography objects?

### ISSUE THREAD

**Issue by ali-ramadhan** [Azzaare/Bibliography.jl#2]
I'd like to look up certain bibliography entries by their BibTeX labels, e.g. `Charney79`, which currently requires me to search through the set entry by entry to see if any of the `item.id` match `Charney79`.

Would an ordered dictionary make more sense? Then lookup can be very easy, e.g.
```
bib = import_bibtex("test.bib")
bib["Charney79"]
```

**Comment by Azzaare** [comment]
Done!

**Comment by ali-ramadhan** [comment]
Awesome, thank you @Azzaare! Should make Documenter citations easier and faster to process!
