### ISSUE TITLE
`import_bibtex` errors upon encountering an article without a volume field

### ISSUE THREAD

**Issue by ali-ramadhan** [Azzaare/Bibliography.jl#6]
Maybe I am not using the BibTeX article class correctly but I use it for arXiv articles and it seems that `import_bibtex` errors once it encounters an article without a volume field. Is it possible to accept articles without a volume field? Or maybe I should update my arXiv BibTeX entries?

```julia
julia> using Bibliography

shell> cat arxiv.bib
@article{Besard16,
        title = {High-level {GPU} programming in {Julia}},
        journal = {arXiv:1604.03410 [cs]},
        author = {Besard, Tim and Verstraete, Pieter and De Sutter, Bjorn},
        year = {2016}
}

julia> import_bibtex("arxiv.bib")
ERROR: Missing the volume field(s).
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] BibInternal.BibTeX.Article(::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::Dict{String,String}) at /home/alir/.julia/packages/BibInternal/mZf28/src/bibtex.jl:102
 [3] BibInternal.BibTeX.Article(::String, ::Dict{String,String}) at /home/alir/.julia/packages/BibInternal/mZf28/src/bibtex.jl:137
 [4] make_bibtex_entry(::String, ::String, ::Dict{String,String}) at /home/alir/.julia/packages/BibInternal/mZf28/src/bibtex.jl:14
 [5] macro expansion at /home/alir/.julia/packages/Automa/fyalL/src/codegen.jl:137 [inlined]
 [6] parse(::String) at /home/alir/.julia/packages/BibParser/Qhq5E/src/bibtex.jl:137
 [7] parse_file at /home/alir/.julia/packages/BibParser/Qhq5E/src/bibtex.jl:144 [inlined]
 [8] import_bibtex(::String) at /home/alir/.julia/packages/Bibliography/ywTv6/src/bibtex.jl:2
 [9] top-level scope at REPL[3]:1
```

Sorry to keep opening issues but hopefully these are easy fixes!

**Comment by ali-ramadhan** [comment]
It seems I cannot give it a blank volume `volume = {}` but I can make the volume a space haha `volume = { }`.

**Comment by ali-ramadhan** [comment]
Some older articles might not have a volume field as well.

```bibtex
@article{Lilly66,
	title = {The {Representation} of {Small}-{Scale} {Turbulence} in {Numerical} {Simulation} {Experiments}.},
	journal = {NCAR Manuscript No. 281},
	author = {Lilly, D K},
	year = {1966},
	volume = { }
}
```

**Comment by Azzaare** [comment]
Thank you for all the issues. I am on my phone so I will answer properly to each later.

I had the same issue with arxiv preprint article. Officially, article in BibTeX has a mandatory volume field. I am planning to set optional rules level in the import functions. By default I will set it up such that arxiv preprints are accepted.

Concerning the parsing errors, it is due to me using a not full BibTeX grammar. The reason being the size of the automata in Automa.jl.
I will make quick fixes, but I am also stuck without answer for some issue in Automa.jl.

Ideally, I would like to have a tokenizer similar as Tokenize.jl, but it is much longer to write than a machine in automa.jl

**Comment by Azzaare** [comment]
@ali-ramadhan I am testing another parser at the moment, it should solve many of the current problems.

As for arxiv entries, based on the output of arxiv itself, we should not use the `@article` entries, but `@misc`. arXiv entries have two possible formats, one old (roughly before 2016 included) and one new (from 2017). Here follow two examples.

```bibtex
@misc{torchcraft,
  author =       {Synnaeve, Gabriel and Nardelli, Nantas and Auvolat, Alex and Chintala, Soumith and Lacroix, Timothée and Lin, Zeming and Richoux, Florian and Usunier Nicolas},
  title =        {TorchCraft: a Library for Machine Learning Research on Real-Time Strategy Games},
  eprint =       {arXiv:1611.00625},
  year =         {2016}
}

@misc{baffier2017experimental,
  title={Experimental Study of Compressed Stack Algorithms in Limited Memory Environments},
  author={Baffier, Jean-François and Diez, Yago and Korman, Matias},
  year={2017},
  eprint={1706.04708},
  archivePrefix={arXiv},
  primaryClass={cs.DS}
}
```

I will update bibliography to output correctly for those two types of entries.

**Comment by Azzaare** [comment]
As long as you use the above `@misc` (or `@eprint`, specific to bibliography.jl, that ensures that the required eprint fields are present), it is now correctly imported/exported
